spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduleManagement
    username: postgres
    password: postgres
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: gettodayschedule@gmail.com
    password: getTodaySchedule123
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          
  main:
    allow-bean-definition-overriding: true
    

